#include "ui/ui.h" 

#include "ui_style.h"

ImVec4 ui_style_text                 = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, ensure dt_text is available via ui.h
ImVec4 ui_style_text_disabled        = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_window_bg            = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_child_bg             = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_popup_bg             = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_border               = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_border_shadow        = {0.00f, 0.00f, 0.00f, 0.00f};
ImVec4 ui_style_frame_bg             = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_frame_bg_hovered     = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x313A4C, 0.9f)
ImVec4 ui_style_frame_bg_active      = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x3A445D, 1.0f)
ImVec4 ui_style_title_bg             = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x161A23, 1.0f)
ImVec4 ui_style_title_bg_active      = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_title_bg_collapsed   = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x1A202C, 0.75f)
ImVec4 ui_style_menu_bar_bg          = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_scrollbar_bg         = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x171923, 0.53f)
ImVec4 ui_style_scrollbar_grab       = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x4A5568, 1.0f)
ImVec4 ui_style_scrollbar_grab_hovered = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x718096, 1.0f)
ImVec4 ui_style_scrollbar_grab_active= {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0xA0AEC0, 1.0f)
ImVec4 ui_style_check_mark           = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_slider_grab          = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_slider_grab_active   = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_button               = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_button_hovered       = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_button_active        = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_header               = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_header_hovered       = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_header_active        = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_separator            = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_separator_hovered    = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_separator_active     = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_resize_grip          = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_resize_grip_hovered  = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_resize_grip_active   = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_tab                  = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_tab_hovered          = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_docking_preview      = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_docking_empty_bg     = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x2D3748, 1.0f)
ImVec4 ui_style_plot_lines           = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x90CDF4, 1.0f)
ImVec4 ui_style_plot_lines_hovered   = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x63B3ED, 1.0f)
ImVec4 ui_style_plot_histogram       = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0xF6AD55, 1.0f)
ImVec4 ui_style_plot_histogram_hovered= {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0xED8936, 1.0f)
ImVec4 ui_style_text_selected_bg     = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder
ImVec4 ui_style_drag_drop_target     = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0xF6E05E, 0.90f)
ImVec4 ui_style_nav_windowing_highlight= {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0xFFFFFF, 0.70f)
ImVec4 ui_style_nav_windowing_dim_bg = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x808080, 0.20f)
ImVec4 ui_style_modal_window_dim_bg  = {0.0f, 0.0f, 0.0f, 0.0f}; // Placeholder, e.g., hexToVec4(0x1A202C, 0.65f)


/*
    colors[ImGuiCol_Text]                 = ui_style_text;
    colors[ImGuiCol_TextDisabled]         = ui_style_text_disabled;
    colors[ImGuiCol_WindowBg]             = ui_style_window_bg;
    colors[ImGuiCol_ChildBg]              = ui_style_child_bg; // Assuming dt_bg_main was intended for child bg as well
    colors[ImGuiCol_PopupBg]              = ui_style_popup_bg;
    colors[ImGuiCol_Border]               = ui_style_border;
    colors[ImGuiCol_BorderShadow]         = ui_style_border_shadow;
    colors[ImGuiCol_FrameBg]              = ui_style_frame_bg;
    colors[ImGuiCol_FrameBgHovered]       = ui_style_frame_bg_hovered;
    colors[ImGuiCol_FrameBgActive]        = ui_style_frame_bg_active;
    colors[ImGuiCol_TitleBg]              = ui_style_title_bg;
    colors[ImGuiCol_TitleBgActive]        = ui_style_title_bg_active;
    colors[ImGuiCol_TitleBgCollapsed]     = ui_style_title_bg_collapsed;
    colors[ImGuiCol_MenuBarBg]            = ui_style_menu_bar_bg;
    colors[ImGuiCol_ScrollbarBg]          = ui_style_scrollbar_bg;
    colors[ImGuiCol_ScrollbarGrab]        = ui_style_scrollbar_grab;
    colors[ImGuiCol_ScrollbarGrabHovered] = ui_style_scrollbar_grab_hovered;
    colors[ImGuiCol_ScrollbarGrabActive]  = ui_style_scrollbar_grab_active;
    colors[ImGuiCol_CheckMark]            = ui_style_check_mark;
    colors[ImGuiCol_SliderGrab]           = ui_style_slider_grab;
    colors[ImGuiCol_SliderGrabActive]     = ui_style_slider_grab_active;
    colors[ImGuiCol_Button]               = ui_style_button;
    colors[ImGuiCol_ButtonHovered]        = ui_style_button_hovered;
    colors[ImGuiCol_ButtonActive]         = ui_style_button_active;
    colors[ImGuiCol_Header]               = ui_style_header;
    colors[ImGuiCol_HeaderHovered]        = ui_style_header_hovered;
    colors[ImGuiCol_HeaderActive]         = ui_style_header_active;
    colors[ImGuiCol_Separator]            = ui_style_separator;
    colors[ImGuiCol_SeparatorHovered]     = ui_style_separator_hovered;
    colors[ImGuiCol_SeparatorActive]      = ui_style_separator_active;
    colors[ImGuiCol_ResizeGrip]           = ui_style_resize_grip;
    colors[ImGuiCol_ResizeGripHovered]    = ui_style_resize_grip_hovered;
    colors[ImGuiCol_ResizeGripActive]     = ui_style_resize_grip_active;
    colors[ImGuiCol_Tab]                  = ui_style_tab;
    colors[ImGuiCol_TabHovered]           = ui_style_tab_hovered;
    //colors[ImGuiCol_TabActive]            = ui_style_tab_active;
    //colors[ImGuiCol_TabUnfocused]         = ui_style_tab_unfocused;
    //colors[ImGuiCol_TabUnfocusedActive]   = ui_style_tab_unfocused_active;
    colors[ImGuiCol_DockingPreview]       = ui_style_docking_preview;
    colors[ImGuiCol_DockingEmptyBg]       = ui_style_docking_empty_bg;
    colors[ImGuiCol_PlotLines]            = ui_style_plot_lines;
    colors[ImGuiCol_PlotLinesHovered]     = ui_style_plot_lines_hovered;
    colors[ImGuiCol_PlotHistogram]        = ui_style_plot_histogram;
    colors[ImGuiCol_PlotHistogramHovered]= ui_style_plot_histogram_hovered;
    colors[ImGuiCol_TextSelectedBg]       = ui_style_text_selected_bg;
    colors[ImGuiCol_DragDropTarget]       = ui_style_drag_drop_target;
    //colors[ImGuiCol_NavHighlight]         = ui_style_nav_highlight;
    colors[ImGuiCol_NavWindowingHighlight]= ui_style_nav_windowing_highlight;
    colors[ImGuiCol_NavWindowingDimBg]    = ui_style_nav_windowing_dim_bg;
    colors[ImGuiCol_ModalWindowDimBg]     = ui_style_modal_window_dim_bg;
*/