#ifndef CNES_VERSION_H
#define CNES_VERSION_H

#define CNES_VERSION_MAJOR 0
#define CNES_VERSION_MINOR 1
#define CNES_VERSION_PATCH 0
#define CNES_VERSION_STRING "0.1.0"
#define CNES_VERSION_STRING_LONG "cNES v" CNES_VERSION_STRING
#define CNES_VERSION_BUILD_DATE __DATE__
#define CNES_VERSION_BUILD_STRING CNES_VERSION_STRING_LONG " (" CNES_VERSION_BUILD_DATE ")"

#endif // CNES_VERSION_H